### ISSUE TITLE
route manual and automatic

### ISSUE THREAD

**Issue by javierpose** [tmuguet/lrm-straightline#1]
How can you create a single route with a manual part with lrm-straightline and an automatic part with Leaflet Routing Machine?

**Comment by tmuguet** [comment]
Hi,

Without more input on what you want to do, it's complicated to give you a definitive answer.

But I've done this for [map2gpx](https://github.com/tmuguet/map2gpx) via [Leaflet.TrackDrawer](https://github.com/tmuguet/Leaflet.TrackDrawer).   
It manages a `LayerGroup` object that consists in a list of routes, each route being computed by Leaflet Routing Machine, either via an automatic routing (osrm, graphhopper, etc.) or via this plugin.

That being said, I'm not using the LRM control; I don't think it's possible to use it as-is in this context.

**Comment by javierpose** [comment]
thank you. I did not see your other plugins, an impressive job.

**Comment by tmuguet** [comment]
> thank you. I did not see your other plugins, an impressive job.

Thanks!   
Let me know if you need anything, I'd be happy to help.
